server:
  port: 9290

spring:
  datasource:
    url: jdbc:mysql://localhost:1353/DB?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false

